# docker-compose run --rm --name gg-client client
version: '3'
services:
  api:
    build: ./global-greet-api
    image: global-greet-api
    container_name: ${API_CONTAINER_NAME}
    environment:
      - API_PORT=${API_CONTAINER_PORT}
      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
      - DB_PORT=${DB_PORT}
    ports:
      - "${LOCAL_HOST_API_PORT}:${API_CONTAINER_PORT}"
    depends_on:
      - database
  client:
    build: ./global-greet-client
    image: global-greet-client
    container_name: ${CLIENT_CONTAINER_NAME}
    environment:
      - API_CONTAINER_NAME=${API_CONTAINER_NAME}
      - API_CONTAINER_PORT=${API_CONTAINER_PORT}
    depends_on:
      - api
  database:
    image: redis:6.2.6-alpine3.15
    container_name: ${DB_CONTAINER_NAME}