FROM golang:1.17-alpine3.15 AS buildingblock
WORKDIR /goCode
COPY . .
RUN go mod download
RUN go build -o ./output/newPassword
FROM scratch
COPY --from=buildingblock /goCode/output/newPassword /newPassword
CMD [ "/newPassword" ]